version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11
      
    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn lint
       
      - run: yarn test


